# Generated by Django 2.0 on 2018-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='year_end',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
