# Generated by Django 2.0 on 2018-03-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMusic', '0002_auto_20180312_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('country', 'Country'), ('audio', 'Audio'), ('artist', 'Artist'), ('playlist', 'Playlist')], max_length=10)),
                ('user_id', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
