# Generated by Django 2.0 on 2018-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMusic', '0005_auto_20180507_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='when',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
